### ISSUE TITLE
Questions about paper(about normalization)

### ISSUE THREAD

**Issue by JudgeLJX** [Zhiyuan-R/Tiger-Diffusion#4]
Hi,

Thanks for the excellent work.

Could you figure out my confusion following:

I run your code on categories chair/car, and the output provides some visualization.
1. According to the x.png/eval.png, it seems each point cloud is normalized into a cube, the chair looks nice, but the car looks like a mess, is that fine?
2. Did you only use the global normalization across the dataset in your work?
3. Did you calculate the metrics with output and **the normalized** original data distribution?
4. If the generations are normalized into a cube, did you reshape them to the original scale (in your paper, the visualizations are normal scale)?

I would appreciate it if you could answer.

**Comment by Zhiyuan-R** [comment]
1. Could you try a little bit longer training for the car? If you still have issues, i can try to reproduce again from my end.
2. I think so.
3. Yes!
(Actually, I follow the same setting as the [PointFlow](https://github.com/stevenygd/PointFlow) )
4. [https://github.com/Zhiyuan-R/Tiger-Diffusion/blob/ca6aaf6a6a3ce084ad9d0252a3ec60555ccedd42/train_generation.py#L210](url)
I think I visualize it after a clipping operation like this. Otherwise, some points will go out of the space.

**Comment by JudgeLJX** [comment]
![Screenshot 2024-07-17 at 22 07 53](https://github.com/user-attachments/assets/0d2aa6ff-1c51-481f-9188-520ed764e23f)
![Screenshot 2024-07-17 at 22 09 33](https://github.com/user-attachments/assets/e891901e-0450-4873-b18d-064c0ec703f4)
Thanks for your quick reply, for the generation. I got the 850 epoch results (samples and x ), do you think this looks good? 

If possible, could you please release your checkpoint and test part?

When I tried to test via $python test_generation.py --category chair --model 'output/train_generation/2024-07-10-19-40-38/epoch_1399.pth'; it shows that the model mismatch with the model in training. I checked the model in the training and testing file. 
In the training file:  has model.module.transformer. .... 
but the testing file: has model.module.global_att. ... instead

Best

**Comment by JudgeLJX** [comment]
If possible, could you please release your checkpoint and test part?

**Comment by fivefingerhill** [comment]
I meet the same problem that the **Model** for denoise in **test_generation.py** is different from that in **train_generation.py**, but not master. it's easy to debug.

**Comment by JudgeLJX** [comment]
> I meet the same problem that the **Model** for denoise in **test_generation.py** is different from that in **train_generation.py**, but not master. it's easy to debug.

Hi, Did you reproduce the experimental values shown in the paper? I didn't achieve it, maybe I got something wrong.
