### ISSUE TITLE
Cannot reproduce the results

### ISSUE THREAD

**Issue by JudgeLJX** [Zhiyuan-R/Tiger-Diffusion#5]
Hi, 

Could you please share which epoch of training you used for evaluation?

I cannot reproduce the results in your paper. I only changed the model in test_generation to match the train_generation.

Thank you

Best

**Comment by Zhiyuan-R** [comment]
Hi,

I am pretty busy for these days. Sorry for not replying in the github issue. I wil find a time to fix the test_generation.py and double check the reproduction of the model for sure.

Best,
Zhiyuan

-------------------------------------------------------------------------------------------------------------------------
PhD Researcher
Computer Vision Lab
Department of Computer Science and Engineering
Michigan State University
________________________________
From: JudgeLJX ***@***.***>
Sent: Friday, August 2, 2024 9:37 AM
To: Zhiyuan-R/Tiger-Diffusion ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Zhiyuan-R/Tiger-Diffusion] Cannot reproduce the results (Issue #5)


Hi,

Could you please share which epoch of training you used for evaluation?

I cannot reproduce the results in your paper. I only changed the model in test_generation to match the train_generation.

Thank you

Best

**Comment by JudgeLJX** [comment]
Hi here are the results of chairs evaluated with training 3000 epochs, 1300epoch does similar results. should I check every epoch, maybe earlier will be better.

For the test file, I only change this line https://github.com/Zhiyuan-R/Tiger-Diffusion/blob/ca6aaf6a6a3ce084ad9d0252a3ec60555ccedd42/test_generation.py#L278C10-L278C20  to Tiger_transformer.

{'1-NN-CD-acc': 0.5513595342636108,
 '1-NN-CD-acc_f': 0.6435045599937439,
 '1-NN-CD-acc_t': 0.4592145085334778,
 '1-NN-EMD-acc': 0.5422960519790649,
 '1-NN-EMD-acc_f': 0.5694863796234131,
 '1-NN-EMD-acc_t': 0.5151057243347168,
 'lgan_cov-CD': 0.4864048361778259,
 'lgan_cov-EMD': 0.5241692066192627,
 'lgan_mmd-CD': 0.0025521295610815287,
 'lgan_mmd-EMD': 0.015459808520972729,
 'lgan_mmd_smp-CD': 0.0024561486206948757,
 'lgan_mmd_smp-EMD': 0.015705913305282593}
'JSD: 0.01740950611375247'

I am looking forward to your reply.

Best.

**Comment by JudgeLJX** [comment]
Hi, I can get the results, 
I'm very sorry about this.
I really appreciate it.

Best
