### ISSUE TITLE
About point cloud visualization

### ISSUE THREAD

**Issue by LauSkygh** [Zhiyuan-R/Tiger-Diffusion#7]
Hello!
Thank you for your excellent work.
The point cloud visualization in your paper looks great. Could you tell me which tool was used to create it? If it was generated using code, could you provide the code?
I would greatly appreciate it if you could answer.

**Comment by Zhiyuan-R** [comment]
Please refer this [link](https://github.com/zekunhao1995/PointFlowRenderer).
